// Build step: read every Markdown file in src/content/research/, parse its
// front-matter, and emit a typed TypeScript module (src/data/research.generated.ts)
// that the app imports. This keeps the Markdown parser (gray-matter) OUT of the
// browser bundle — parsing happens once at build/dev time in Node.
//
// Run automatically via the "build" and "predev" npm scripts. Safe to run with
// zero content files (emits an empty array).

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, "..");
const CONTENT_DIR = path.join(ROOT, "src", "content", "research");
const OUT_FILE = path.join(ROOT, "src", "data", "research.generated.ts");

// js-yaml (used by gray-matter) auto-parses `2026-07-01` into a Date object.
// Normalise any date-ish value back to a plain YYYY-MM-DD string.
function toDateStr(v) {
  if (v == null) return undefined;
  if (v instanceof Date) return v.toISOString().slice(0, 10);
  return String(v);
}

function readArticles() {
  if (!fs.existsSync(CONTENT_DIR)) return [];
  const files = fs.readdirSync(CONTENT_DIR).filter((f) => f.endsWith(".md") || f.endsWith(".mdx"));
  const articles = [];

  for (const file of files) {
    const raw = fs.readFileSync(path.join(CONTENT_DIR, file), "utf8");
    const { data, content } = matter(raw);
    const slug = data.slug || file.replace(/\.mdx?$/, "");

    if (!data.title) {
      console.warn(`  [skip] ${file}: missing "title" in front-matter`);
      continue;
    }

    articles.push({
      slug,
      title: data.title,
      excerpt: data.excerpt || "",
      category: data.category || "Uncategorised",
      metaTitle: data.metaTitle,
      metaDescription: data.metaDescription || data.excerpt,
      canonical: data.canonical || `https://valuationnode.com/research/${slug}`,
      ogImage: data.ogImage || "/og-image.png",
      publishedAt: toDateStr(data.publishedAt),
      updatedAt: toDateStr(data.updatedAt),
      readingTime: typeof data.readingTime === "number" ? data.readingTime : undefined,
      author: data.author || "Srinath Gajji",
      methodologySummary: data.methodologySummary,
      whereIMightBeWrong: data.whereIMightBeWrong,
      citationFormat: data.citationFormat,
      modelDownloadUrl: data.modelDownloadUrl,
      githubUrl: data.githubUrl,
      updateLog: Array.isArray(data.updateLog) ? data.updateLog : undefined,
      keyTakeaways: Array.isArray(data.keyTakeaways) ? data.keyTakeaways : undefined,
      content: content.trim(),
    });
  }

  // Drop undefined keys so the generated file stays clean, then sort newest-first.
  const cleaned = articles.map((a) =>
    Object.fromEntries(Object.entries(a).filter(([, v]) => v !== undefined))
  );
  cleaned.sort((a, b) => {
    const da = a.publishedAt ? Date.parse(a.publishedAt) : 0;
    const db = b.publishedAt ? Date.parse(b.publishedAt) : 0;
    return db - da;
  });
  return cleaned;
}

function main() {
  const articles = readArticles();
  const banner =
    "// AUTO-GENERATED by scripts/generateArticles.js — do not edit by hand.\n" +
    "// Source of truth: src/content/research/*.md\n";
  const body =
    `import type { ResearchArticleData } from "./researchTypes";\n\n` +
    `export const RESEARCH_ARTICLES: ResearchArticleData[] = ${JSON.stringify(articles, null, 2)};\n`;

  fs.mkdirSync(path.dirname(OUT_FILE), { recursive: true });
  fs.writeFileSync(OUT_FILE, banner + "\n" + body, "utf8");
  console.log(`generateArticles: wrote ${articles.length} article(s) to src/data/research.generated.ts`);
}

main();
