// AUTO-GENERATED by scripts/generateArticles.js — do not edit by hand.
// Source of truth: src/content/research/*.md

import type { ResearchArticleData } from "./researchTypes";

export const RESEARCH_ARTICLES: ResearchArticleData[] = [
  {
    "slug": "how-the-valuation-node-approaches-research",
    "title": "How The Valuation Node Approaches Research",
    "excerpt": "The principles behind every analysis published here — transparency of assumptions, primary sources, and an honest account of where the analysis could be wrong.",
    "category": "Methodology",
    "metaTitle": "How The Valuation Node Approaches Research - The Valuation Node",
    "metaDescription": "The research method behind The Valuation Node — how assumptions are stated, how sources are chosen, and how uncertainty is disclosed in every published analysis.",
    "canonical": "https://valuationnode.com/research/how-the-valuation-node-approaches-research",
    "ogImage": "/og-image.png",
    "publishedAt": "2026-07-01",
    "updatedAt": "2026-07-06",
    "readingTime": 5,
    "author": "Srinath Gajji",
    "methodologySummary": "Every published analysis states its assumptions up front, works from primary sources, and ends with an explicit account of what could make the conclusion wrong.",
    "citationFormat": "Gajji, S. (2026). \"How The Valuation Node Approaches Research.\" The Valuation Node. https://valuationnode.com/research/how-the-valuation-node-approaches-research",
    "keyTakeaways": [
      "Assumptions are stated before conclusions, never buried inside them.",
      "Numbers come from primary filings and disclosures, not second-hand aggregators.",
      "Every analysis names the conditions under which it would be wrong."
    ],
    "content": "Research is only as trustworthy as the assumptions underneath it. The aim of this note is to make those assumptions visible, so that any analysis published here can be checked, challenged, and rebuilt by a reader who disagrees.\n\n## Assumptions before conclusions\n\nA valuation is a chain of assumptions — growth, margins, reinvestment, discount rate — that produce a number at the end. The number is easy to quote and easy to misuse. The assumptions are what actually matter.\n\nEvery analysis here states its key assumptions first, in plain language, and shows how sensitive the conclusion is to each one. If a two-percentage-point change in an assumption flips the conclusion, that fragility is disclosed rather than hidden.\n\n## Primary sources over aggregators\n\nFigures are drawn from primary disclosures — annual reports, exchange filings, and regulatory documents — rather than second-hand data aggregators that can carry classification errors or stale numbers. Where a figure is an estimate, it is labelled as one.\n\nThis is slower, but it means a reader can trace any number back to the document it came from.\n\n## An honest account of uncertainty\n\nNo analysis is complete without a clear statement of what could make it wrong. Each piece ends with the specific conditions — a competitive shift, a regulatory change, an assumption that proves too optimistic — under which the conclusion would no longer hold.\n\nThe goal is not to sound certain. It is to be useful to someone making a real decision, who needs to know not just the answer but the confidence behind it.\n\n## Independence\n\nNothing published here is investment advice, and no analysis is a recommendation to buy or sell. The work is educational: a transparent worked example of how a business can be reasoned about, so that readers can build and defend their own view."
  }
];
